// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRek5ZxNcRPa0bLWKP114Vih-jCr8X_-M',
    appId: '1:284740788:web:de926fa0832024339a5be1',
    messagingSenderId: '284740788',
    projectId: 'moss-poc-e14fe',
    authDomain: 'moss-poc-e14fe.firebaseapp.com',
    databaseURL: 'https://moss-poc-e14fe-default-rtdb.firebaseio.com',
    storageBucket: 'moss-poc-e14fe.firebasestorage.app',
    measurementId: 'G-WL2J697870',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8VBVcqs3do6mwayGTmKkSaRd04JbhvYM',
    appId: '1:284740788:android:5283780f17857d5c9a5be1',
    messagingSenderId: '284740788',
    projectId: 'moss-poc-e14fe',
    databaseURL: 'https://moss-poc-e14fe-default-rtdb.firebaseio.com',
    storageBucket: 'moss-poc-e14fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr1SC84lOBYel-UI1WHVdGAMHk6mQnCDA',
    appId: '1:284740788:ios:26869027b497ffb69a5be1',
    messagingSenderId: '284740788',
    projectId: 'moss-poc-e14fe',
    databaseURL: 'https://moss-poc-e14fe-default-rtdb.firebaseio.com',
    storageBucket: 'moss-poc-e14fe.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr1SC84lOBYel-UI1WHVdGAMHk6mQnCDA',
    appId: '1:284740788:ios:26869027b497ffb69a5be1',
    messagingSenderId: '284740788',
    projectId: 'moss-poc-e14fe',
    databaseURL: 'https://moss-poc-e14fe-default-rtdb.firebaseio.com',
    storageBucket: 'moss-poc-e14fe.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRek5ZxNcRPa0bLWKP114Vih-jCr8X_-M',
    appId: '1:284740788:web:827fe56e4bcf51059a5be1',
    messagingSenderId: '284740788',
    projectId: 'moss-poc-e14fe',
    authDomain: 'moss-poc-e14fe.firebaseapp.com',
    databaseURL: 'https://moss-poc-e14fe-default-rtdb.firebaseio.com',
    storageBucket: 'moss-poc-e14fe.firebasestorage.app',
    measurementId: 'G-4G8TL152KW',
  );
}
